# Generated by Django 4.1.5 on 2023-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposito', models.CharField(max_length=256)),
                ('fechaObjetivo', models.DateField()),
                ('completado', models.BooleanField(null=True)),
                ('fechaCompletado', models.DateField(null=True)),
            ],
        ),
    ]
