# Generated by Django 4.1.6 on 2023-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('direccion', models.CharField(max_length=255, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=255, verbose_name='telefono')),
                ('personaContacto', models.CharField(max_length=255, verbose_name='persona de contacto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion')),
            ],
        ),
    ]
