# Generated by Django 4.1.6 on 2023-02-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(upload_to='ventaCoches', verbose_name='foto coche')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación ')),
            ],
        ),
    ]
