# Generated by Django 4.1.6 on 2023-02-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaCoches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receta',
            new_name='Coche',
        ),
    ]
