# Generated by Django 4.1.6 on 2023-02-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventaCoches', '0002_rename_receta_coche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='coche',
            options={'ordering': ['-fechaCreacion'], 'verbose_name': 'coche', 'verbose_name_plural': 'coches'},
        ),
        migrations.AddField(
            model_name='coche',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
            preserve_default=False,
        ),
    ]
